version: '2'

services:
    fhem:
        expose:
            - "8083"
        ports:
            - "8083:8083"
        build: fhem
        privileged: true
        volumes:
            - ./fhem/data/:/opt/fhem/
        networks:
            - code-network
        depends_on:
            - "mysql"

    mysql:
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
